### PR TITLE
OCE-55: Add topology(link) support to the OpenNMS Direct datasource

### PR DESCRIPTION
**Pull request by mattixtech**
- Added support to the direct inventory data source for consuming link data from OpenNMS

Tested manually using the topology generator shell command.

This depends on the integration API changes here: https://github.com/OpenNMS/opennms-integration-api/pull/10

Jira: https://issues.opennms.org/browse/OCE-55

### CODE REVIEW

**Comment by mattixtech** [comment]
Addressed feedback from the integration API review. Will re-test once all feedback is implemented.

**Review by smith-opennms — APPROVED** [review]
LGTM

**Comment by mattixtech** [comment]
Pushed a bunch of changes to handle additional edge types that I hadn't supported in first patch sets.

**Comment by mattixtech** [comment]
I suspect the test will continue to fail until the API changes are merged.

**Comment by mattixtech** [comment]
@j-white the smoke test failure appears to be due to a recent version of the horizon docker image. The tests pass locally for me when I use a version from last week. I pulled the latest horizon docker image and reproduced the smoke test failure.

**Comment by j-white** [comment]
@mattixtech try re-basing over the latest master, I think you need this commit for it to pass: https://github.com/OpenNMS/oce/commit/2ba898bd99dcba7dc1f532a08dfd8ce3ba7bbfa2

**Review by j-white — APPROVED** [review]

**Pull request merged**
